//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluacionAprendizaje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PremiosCompetidor
    {
        public int id { get; set; }
        public int cantidadPremios { get; set; }
        public int anio { get; set; }
        public Nullable<int> idCompetidor { get; set; }
    
        public virtual Competidor Competidor { get; set; }
    }
}
